sonar.projectKey=python-expense-tracker
sonar.projectName=Python Expense Tracker
sonar.projectVersion=1.0

sonar.sources=expense_tracker
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10,3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.exclusions=build/**,dist/**,.venv/**
